# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:126c0e45cefb24c8c75650a0e7ca08b4f4be288e4c643608487e8abfb0578175

    working_directory: ~/nteract

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - ~/.npm
            - ./node_modules
            - ~/.jestcache
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:lint
      - run: npm run test -- --cacheDirectory=~/.jestcache
      - run: npm run test:flow
      - run: npm run test:conformance
      - run:
          name: Build Apps
          command: npm run build:apps
          no_output_timeout: 60m
